services:
  neuvector: neuvector

steps:
- task: Docker@2
  displayName: Build image
  inputs:
      command: build
      Dockerfile: Backend/Dockerfile
      buildContext: '**'
      repository: 'backend'
      tags: '$(Build.BuildId)'
      addPipelineData: false
- task: DownloadSecureFile@1
  name: neuvectorLicense
  displayName: Get NeuVector license
  inputs:
    secureFile: 'neuvector-license.txt'
- task: NeuVectorScan@1
  displayName: Scan image with NeuVector
  inputs:
    controllerType: local
    controllerPort: 10443
    controllerLicense: '$(neuvectorLicense.secureFilePath)'
    repository: 'backend'
    tags: '$(Build.BuildId)'
    failOnHighSeverityThreshold: true
    highSeverityThreshold: '1'
    failOnMediumSeverityThreshold: true
    mediumSeverityThreshold: '3'
- script: |
    docker tag backend:$(Build.BuildId) gallery.azurecr.io/backend:$(Build.BuildId)
  displayName: Tag for private registry
- task: Docker@2
  displayName: Push to private registry
  inputs:
    command: push
    containerRegistry: 'gallery.azurecr.io'
    repository: 'backend'
    tags: '$(Build.BuildId)'

resources:
  containers:
  - container: neuvector
    image: neuvector/controller:latest
    endpoint: 'Docker Hub'
    ports:
      - 18300:18300
      - 18301:18301
      - 18400:18400
      - 18401:18401
      - 10443:10443
    volumes:
      - /lib/modules:/lib/modules
      - /var/neuvector:/var/neuvector
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/host/cgroup
      - /proc:/host/proc
    options: --pid=host --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --cap-add=SYS_PTRACE --cap-add=IPC_LOCK --security-opt apparmor:unconfined --env CLUSTER_JOIN_ADDR=neuvector --env CTRL_SERVER_PORT=10443