apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     {{ .Values.logLevel }}
        Daemon        off
        Parsers_File  /fluent-bit/etc/parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    
    @INCLUDE input-syslog-neuvector.conf
{{- if .Values.enableStandardOutput }}
    @INCLUDE output-stdout.conf
{{- end }}
{{- if .Values.enableAzurePlugin }}
    @INCLUDE output-azure.conf
  output-azure.conf: |
    [OUTPUT]
        Name        azure
        Match       *
        Log_Type    Neuvector
        Customer_ID ${FLUENTBIT_AZURE_CUSTOMER_ID}
        Shared_Key  ${FLUENTBIT_AZURE_SHARED_KEY}
{{- end }}
  input-syslog-neuvector.conf: |
    [INPUT]
        Name   syslog
        Mode   tcp
        Listen 0.0.0.0
        Port   5140
        Parser syslog-rfc5424
        Tag    syslog.default
  output-stdout.conf: |
    [OUTPUT]
        Name        stdout
        Match       *
