{{- if .Values.enableSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
stringData:
  azure_log_workspace_id: {{ .Values.azure_log_workspace_id }}
  azure_log_workspace_shared_key: {{ .Values.azure_log_workspace_shared_key }}
  datadog_api_key: {{ .Values.datadog_api_key }}
{{- end }}